sudo: true
language: rust
cache: cargo

#addons:
#  apt:
#    packages:
#    - libssl-dev

rust:
  - stable
  - beta
  - nightly

env:
  global:
  - CARGO_MAKE_RUN_CODECOV=true
  - RUSTFLAGS="-C link-dead-code"
  - RUST_BACKTRACE=1
  - SCCACHE_DIR="$HOME/.cargo/sccache"

before_install:
  - sh ci/install-cargo-make.sh
  - cargo make ci-setup-flow

script:
  - cargo make ci-flow

deploy:
  provider: script
  script: cargo make publish-flow
  on:
    tags: true
    repo: althonos/opticaldisc
    rust: stable

notifications:
  email:
  - althonosdev@gmail.com
