[package]
name = "opticaldisc"
version = "0.1.0"
authors = ["Martin Larralde <martin.larralde@ens-cachan.fr>"]

[dependencies]
memchr = "^2.0"
nom = "4.0.0-beta3"
btoi = "^0.3"
error-chain = { version = "^0.11", default-features = false }
chrono = { version = "^0.4", default-features = false }
